"""empty message

Revision ID: 07579ea8ea4a
Revises: 5c73b7b1d2f2
Create Date: 2020-06-30 23:39:51.326178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07579ea8ea4a'
down_revision = '5c73b7b1d2f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))

    op.execute('UPDATE todos SET completed = False WHERE completed is NULL')

    op.alter_column('todos', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
